name: docker-build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: "Checkout repository"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Get package.json version
        id: package-version
        run: |
            echo "Reading package.json from ./package.json"
            PACKAGE_VERSION=$(cat ./package.json | jq '.version' | tr -d '"')
            echo ::set-output name=current-version::$PACKAGE_VERSION
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: veneliniliev/prerender-docker:${{ steps.package-version.outputs.current-version}}